# Generated by Django 6.0.2 on 2026-02-09 09:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('could_use_for_eating', models.BooleanField(blank=True, default=True)),
                ('wikipedia', models.URLField(default='https://en.wikipedia.org/', unique_for_date='delivered_at')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('discount_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('invoice', models.FileField(blank=True, upload_to='')),
                ('user_uuid', models.UUIDField(editable=False)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh_period', models.DurationField(default=datetime.timedelta(days=20), help_text='Fresh time expiration for milk')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('price', models.FloatField(default=47.0)),
                ('milk', models.ManyToManyField(to='lesson_5.products', verbose_name='This is a milk')),
            ],
        ),
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh_period', models.DurationField(default=datetime.timedelta(days=5), help_text='Fresh time expiration of meat')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('price', models.FloatField(default=0.0)),
                ('meat', models.ManyToManyField(to='lesson_5.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh_period', models.DurationField(default=datetime.timedelta(days=30), help_text='Fresh time expiration of the cheese')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('price', models.FloatField(default=50.0)),
                ('cheese', models.ManyToManyField(to='lesson_5.products', verbose_name='This cheese is a product for eating')),
            ],
        ),
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh_period', models.DurationField(default=datetime.timedelta(days=3), help_text='Fresh time expiration of bread')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('price', models.FloatField(default=30.0)),
                ('bread', models.ManyToManyField(to='lesson_5.products', verbose_name='This is a bread')),
            ],
        ),
        migrations.CreateModel(
            name='Sausage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh_period', models.DurationField(default=datetime.timedelta(days=15), help_text='Fresh time expiration of sausage')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('price', models.FloatField(default=50.0)),
                ('sausage', models.ManyToManyField(to='lesson_5.products', verbose_name='This is a sausage from meat')),
            ],
        ),
    ]
