# Generated by Django 6.0.2 on 2026-02-10 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='fresh_period',
            field=models.DurationField(default=datetime.timedelta(days=3), help_text='Fresh time expiration of bread', null=True),
        ),
        migrations.AlterField(
            model_name='bread',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bread',
            name='price',
            field=models.FloatField(default=30.0, null=True),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='fresh_period',
            field=models.DurationField(default=datetime.timedelta(days=30), help_text='Fresh time expiration of the cheese', null=True),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='price',
            field=models.FloatField(default=50.0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='discount_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='meat',
            name='fresh_period',
            field=models.DurationField(default=datetime.timedelta(days=5), help_text='Fresh time expiration of meat', null=True),
        ),
        migrations.AlterField(
            model_name='meat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='meat',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='milk',
            name='fresh_period',
            field=models.DurationField(default=datetime.timedelta(days=20), help_text='Fresh time expiration for milk', null=True),
        ),
        migrations.AlterField(
            model_name='milk',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='milk',
            name='price',
            field=models.FloatField(default=47.0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='could_use_for_eating',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sausage',
            name='fresh_period',
            field=models.DurationField(default=datetime.timedelta(days=15), help_text='Fresh time expiration of sausage', null=True),
        ),
        migrations.AlterField(
            model_name='sausage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sausage',
            name='price',
            field=models.FloatField(default=50.0, null=True),
        ),
    ]
