# Generated by Django 6.0.2 on 2026-02-12 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0003_alter_cheese_managers_alter_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_5.client')),
                ('products', models.ManyToManyField(to='lesson_5.products')),
            ],
        ),
    ]
