# Generated by Django 6.0.2 on 2026-02-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0005_client_birthday_alter_client_discount_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='wikipedia',
            field=models.URLField(blank=True, default='https://en.wikipedia.org/', null=True, unique_for_date='delivered_at'),
        ),
    ]
