# Generated by Django 6.0.2 on 2026-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0008_alter_products_wikipedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='wikipedia',
            field=models.URLField(blank=True, default='https://en.wikipedia.org/'),
        ),
    ]
