# Generated by Django 6.0.2 on 2026-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0009_alter_products_wikipedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='could_use_for_eating',
            field=models.BooleanField(default=True),
        ),
    ]
